alias p="pmset displaysleepnow"
alias l="ls -la"
alias gs="git status"
alias ga="git add"
alias gm="git commit -m"
alias gma="git commit -a -m"
alias gmm="git commit"
alias gl="git log"
alias glo="git log --oneline"
alias gr="git revert -m"
alias gp="git push"
alias sdd="clear"
alias gc="git checkout"
alias v="vim"
alias c="cat="
alias gst="git stash"
alias gi="touch .gitignore"
alias rmd="rm -Rf"
alias 42="~/code/42"
alias g="gcc -Wall -Wextra -Werror"
alias chm="chmod -R  755  *"
alias work='cd /home/pelluro/Documents/Work && ls'
alias web='cd /var/www/html/Perso && ls'
alias ws='cd /home/pelluro/Documents/WebStorm-193.6015.40/bin && ./webstorm.sh&'
alias ps='cd /home/pelluro/Documents/PhpStorm-2018.3/PhpStorm-183.4284.150/bin && ./phpstorm.sh&'
alias is='cd /home/pelluro/Documents/idea-IU-193.6015.39/bin && ./idea.sh&'
alias cl='cd /home/pelluro/Documents/clion-2019.1.2/bin && ./clion.sh&'
alias gk='cd /home/pelluro/Documents/gitkraken && ./gitkraken&'
alias dg='cd /home/pelluro/Documents/DataGrip-2019.1.1/bin && ./datagrip.sh&'
alias postman='cd /home/pelluro/Documents/Postman/app && ./Postman&'
alias azerty='setxkbmap fr'
alias qwerty='setxkbmap us'
alias off='shutdown -h now'
alias reset='source ~/.zshrc'
alias gobash='chsh -s /bin/bash'
